# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmbrowse < Formula
  desc "Simple and elegant cli AWS SSM parameter browser."
  homepage "https://github.com/bnaydenov/ssmbrowse"
  version "0.2.2"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bnaydenov/ssmbrowse/releases/download/v0.2.2/ssmbrowse_darwin_arm64.zip"
      sha256 "540c3f1df0dff7a57edf141016f8f07c18d71620f1411971da56ad8d39c8cefa"

      def install
        bin.install "ssmbrowse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bnaydenov/ssmbrowse/releases/download/v0.2.2/ssmbrowse_darwin_amd64.zip"
      sha256 "144ba4b3e417eb3212126444873efc4cde273a490d61c89e11f2181d53100ca3"

      def install
        bin.install "ssmbrowse"
      end
    end
  end
end
