# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmbrowse < Formula
  desc "Simple and elegant cli AWS SSM parameter browser."
  homepage "https://github.com/bnaydenov/ssmbrowse"
  version "2.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bnaydenov/ssmbrowse/releases/download/v2.0.1/ssmbrowse_darwin_arm64.zip"
      sha256 "cf9642941bc01a1f6222ac6b08e59c0e59c00fbf5387c39e378cf160413079d6"

      def install
        bin.install "ssmbrowse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bnaydenov/ssmbrowse/releases/download/v2.0.1/ssmbrowse_darwin_amd64.zip"
      sha256 "8c3926f02389442c7b56cb1886703e96b25b29dc32f86b1cb5e128221e08c71c"

      def install
        bin.install "ssmbrowse"
      end
    end
  end
end
